GET http://localhost:3000/ 

###

GET http://localhost:3000/grades HTTP/1.1

###
GET http://localhost:3000/grades/3 HTTP/1.1

###

POST http://localhost:3000/grades HTTP/1.1
content-type: application/json

{
  "id": 4,
  "name": "Och1",
  "course": "CS572",
  "grage": 99
}

###

DELETE http://localhost:3000/grades/2 HTTP/1.1

